export { default as Navbar } from "./Navbar/Navbar"
export { default as Footer } from "./Footer/Footer"
export { default as NavigationDots } from "./NavigationDots"
export { default as SocialMedia } from "./SocialMedia"
export { default as PlayButton } from "./PlayButton"